version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DB_CONNECTION_STRING=mongodb://admin:password@mongo:27017/infineon-task?authSource=admin
      - PORT=8000
      - POPULATE=false
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE_URL: http://localhost:8000  # For SSH connections
        #VITE_BASE_URL: http://backend:8000  # For in machine connections
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
